spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 000ed3f206b85c
    password: c84c2726a21e91
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/cronograma
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  security:
    token:
      secret: "faltatempo"
  cors:
    origin: "http://localhost:3000"